[package]
name = "little-wizard-file-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notan = "0.9.5"
toml = "0.7.3"
serde = "1.0.160"
serde-hex = "0.1.0"
